import type { EditorThemeClasses } from "lexical"

export const editorTheme: EditorThemeClasses = {
  root: "lexical-root outline-none w-full max-w-full cursor-text",
  paragraph: "lexical-paragraph",
  text: {
    bold: "font-semibold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    underlineStrikethrough: "underline line-through",
    code: "lexical-inline-code",
    highlight: "lexical-highlight",
    subscript: "align-sub text-[0.75em]",
    superscript: "align-super text-[0.75em]",
  },
  heading: {
    h1: "lexical-h1",
    h2: "lexical-h2",
    h3: "lexical-h3",
    h4: "lexical-h4",
  },
  list: {
    ul: "lexical-ul",
    ol: "lexical-ol",
    listitem: "lexical-listitem",
    listitemChecked: "lexical-listitem--checked",
    listitemUnchecked: "lexical-listitem--unchecked",
    nested: { listitem: "lexical-nested-listitem" },
  },
  link: "lexical-link",
  quote: "lexical-blockquote",
  code: "lexical-code-block",
  codeHighlight: {
    atrule: "token-atrule",
    attr: "token-attr",
    boolean: "token-boolean",
    builtin: "token-builtin",
    cdata: "token-cdata",
    char: "token-char",
    class: "token-class",
    "class-name": "token-class-name",
    comment: "token-comment",
    constant: "token-constant",
    deleted: "token-deleted",
    doctype: "token-doctype",
    entity: "token-entity",
    function: "token-function",
    important: "token-important",
    inserted: "token-inserted",
    keyword: "token-keyword",
    namespace: "token-namespace",
    number: "token-number",
    operator: "token-operator",
    prolog: "token-prolog",
    property: "token-property",
    punctuation: "token-punctuation",
    regex: "token-regex",
    selector: "token-selector",
    string: "token-string",
    symbol: "token-symbol",
    tag: "token-tag",
    url: "token-url",
    variable: "token-variable",
  },
  table: "lexical-table",
  tableScrollableWrapper: "lexical-table-scroll-wrapper",
  tableCell: "lexical-table-cell",
  tableRow: "lexical-table-row",
  tableCellHeader: "lexical-table-cell--header",
  tableCellSelected: "lexical-table-cell-selected",
}
