export interface EmojiItem {
  char: string;
  name: string;
  category: string;
  keywords: string[];
}

export const EMOJIS: EmojiItem[] = [
  // Smileys & Emotion
  { char: '😀', name: 'grinning', category: 'Smileys', keywords: ['smile', 'happy', 'face', 'grin'] },
  { char: '😃', name: 'smiley', category: 'Smileys', keywords: ['smile', 'happy', 'face', 'joy'] },
  { char: '😄', name: 'smile', category: 'Smileys', keywords: ['smile', 'happy', 'face', 'joy', 'laugh'] },
  { char: '😁', name: 'grin', category: 'Smileys', keywords: ['smile', 'happy', 'face', 'teeth'] },
  { char: '😆', name: 'laughing', category: 'Smileys', keywords: ['smile', 'happy', 'face', 'laugh', 'satisfied'] },
  { char: '😅', name: 'sweat_smile', category: 'Smileys', keywords: ['smile', 'happy', 'face', 'sweat', 'relief'] },
  { char: '😂', name: 'joy', category: 'Smileys', keywords: ['tear', 'laugh', 'cry', 'happy', 'lol'] },
  { char: '🤣', name: 'rofl', category: 'Smileys', keywords: ['tear', 'laugh', 'floor', 'rolling', 'lol'] },
  { char: '😊', name: 'blush', category: 'Smileys', keywords: ['smile', 'happy', 'face', 'blush', 'shy'] },
  { char: '😇', name: 'innocent', category: 'Smileys', keywords: ['halo', 'angel', 'face', 'heaven'] },
  { char: '🙂', name: 'slight_smile', category: 'Smileys', keywords: ['face', 'smile'] },
  { char: '🙃', name: 'upside_down', category: 'Smileys', keywords: ['face', 'flipped', 'silly'] },
  { char: '😉', name: 'wink', category: 'Smileys', keywords: ['face', 'wink', 'flirt'] },
  { char: '😌', name: 'relieved', category: 'Smileys', keywords: ['face', 'relief', 'satisfied', 'calm'] },
  { char: '😍', name: 'heart_eyes', category: 'Smileys', keywords: ['love', 'face', 'heart', 'crush'] },
  { char: '🥰', name: 'smiling_face_with_three_hearts', category: 'Smileys', keywords: ['love', 'face', 'hearts', 'affection'] },
  { char: '😘', name: 'kissing_heart', category: 'Smileys', keywords: ['love', 'kiss', 'face', 'blow'] },
  { char: '😗', name: 'kissing', category: 'Smileys', keywords: ['kiss', 'face'] },
  { char: '😙', name: 'kissing_smiling_eyes', category: 'Smileys', keywords: ['kiss', 'face', 'smile'] },
  { char: '😚', name: 'kissing_closed_eyes', category: 'Smileys', keywords: ['kiss', 'face', 'blush'] },
  { char: '😋', name: 'yum', category: 'Smileys', keywords: ['tongue', 'face', 'delicious', 'yummy', 'food'] },
  { char: '😛', name: 'stuck_out_tongue', category: 'Smileys', keywords: ['tongue', 'face', 'silly'] },
  { char: '😝', name: 'stuck_out_tongue_closed_eyes', category: 'Smileys', keywords: ['tongue', 'face', 'silly', 'squint'] },
  { char: '😜', name: 'stuck_out_tongue_winking_eye', category: 'Smileys', keywords: ['tongue', 'face', 'silly', 'wink'] },
  { char: '🤪', name: 'zany', category: 'Smileys', keywords: ['face', 'crazy', 'silly', 'goofy'] },
  { char: '🤨', name: 'raised_eyebrow', category: 'Smileys', keywords: ['face', 'suspicious', 'skeptical'] },
  { char: '🧐', name: 'monocle', category: 'Smileys', keywords: ['face', 'monocle', 'classy', 'thinking'] },
  { char: '🤓', name: 'nerd', category: 'Smileys', keywords: ['face', 'nerd', 'geek', 'glasses'] },
  { char: '😎', name: 'sunglasses', category: 'Smileys', keywords: ['face', 'cool', 'sunglasses', 'chill'] },
  { char: '🥸', name: 'disguised', category: 'Smileys', keywords: ['face', 'disguise', 'glasses', 'mustache'] },
  { char: '🤩', name: 'star_struck', category: 'Smileys', keywords: ['face', 'stars', 'eyes', 'wow', 'excited'] },
  { char: '🥳', name: 'partying', category: 'Smileys', keywords: ['face', 'party', 'celebrate', 'horn', 'hat'] },
  { char: '😏', name: 'smirk', category: 'Smileys', keywords: ['face', 'smirk', 'sly', 'flirt'] },
  { char: '😒', name: 'unamused', category: 'Smileys', keywords: ['face', 'meh', 'bored', 'unimpressed'] },
  { char: '😞', name: 'disappointed', category: 'Smileys', keywords: ['face', 'sad', 'upset'] },
  { char: '😔', name: 'pensive', category: 'Smileys', keywords: ['face', 'sad', 'thoughtful'] },
  { char: '😟', name: 'worried', category: 'Smileys', keywords: ['face', 'worried', 'nervous'] },
  { char: '😕', name: 'confused', category: 'Smileys', keywords: ['face', 'confused', 'puzzled'] },
  { char: '🙁', name: 'slight_frown', category: 'Smileys', keywords: ['face', 'frown', 'sad'] },
  { char: '☹️', name: 'frowning', category: 'Smileys', keywords: ['face', 'frown', 'sad', 'upset'] },
  { char: '😣', name: 'persevere', category: 'Smileys', keywords: ['face', 'struggle', 'sad'] },
  { char: '😖', name: 'confounded', category: 'Smileys', keywords: ['face', 'confused', 'struggle'] },
  { char: '😫', name: 'tired', category: 'Smileys', keywords: ['face', 'tired', 'yawn', 'exhausted'] },
  { char: '😩', name: 'weary', category: 'Smileys', keywords: ['face', 'tired', 'weary', 'exhausted'] },
  { char: '🥺', name: 'pleading', category: 'Smileys', keywords: ['face', 'begging', 'sad', 'puppy', 'eyes'] },
  { char: '😢', name: 'cry', category: 'Smileys', keywords: ['face', 'sad', 'tear', 'cry'] },
  { char: '😭', name: 'sob', category: 'Smileys', keywords: ['face', 'sad', 'tear', 'cry', 'sobbing'] },
  { char: '😤', name: 'triumph', category: 'Smileys', keywords: ['face', 'angry', 'steam', 'huff'] },
  { char: '😠', name: 'angry', category: 'Smileys', keywords: ['face', 'angry', 'mad', 'annoyed'] },
  { char: '😡', name: 'rage', category: 'Smileys', keywords: ['face', 'angry', 'mad', 'pout', 'rage'] },
  { char: '🤬', name: 'cursing', category: 'Smileys', keywords: ['face', 'angry', 'swear', 'cuss'] },
  { char: '🤯', name: 'exploding_head', category: 'Smileys', keywords: ['face', 'mind', 'blown', 'mindblown', 'explosion'] },
  { char: '😳', name: 'flushed', category: 'Smileys', keywords: ['face', 'flushed', 'blush', 'embarrassed', 'shock'] },
  { char: '🥵', name: 'hot', category: 'Smileys', keywords: ['face', 'hot', 'heat', 'sweat', 'summer'] },
  { char: '🥶', name: 'cold', category: 'Smileys', keywords: ['face', 'cold', 'freeze', 'ice', 'winter'] },
  { char: '😱', name: 'scream', category: 'Smileys', keywords: ['face', 'scream', 'fear', 'shock', 'horror'] },
  { char: '😨', name: 'fearful', category: 'Smileys', keywords: ['face', 'fear', 'scared', 'shock'] },
  { char: '😰', name: 'cold_sweat', category: 'Smileys', keywords: ['face', 'fear', 'sweat', 'nervous'] },
  { char: '😥', name: 'sad_relieved', category: 'Smileys', keywords: ['face', 'sweat', 'relief', 'sad'] },
  { char: '😓', name: 'sweat', category: 'Smileys', keywords: ['face', 'sweat', 'sad', 'nervous'] },
  { char: '🤗', name: 'hug', category: 'Smileys', keywords: ['face', 'hug', 'huggy', 'open', 'hands'] },
  { char: '🤔', name: 'thinking', category: 'Smileys', keywords: ['face', 'thinking', 'thought', 'ponder'] },
  { char: '🫣', name: 'peeking', category: 'Smileys', keywords: ['face', 'peek', 'eye', 'fear', 'shy'] },
  { char: '🤭', name: 'giggle', category: 'Smileys', keywords: ['face', 'hand', 'mouth', 'giggle', 'shame'] },
  { char: '🫢', name: 'gasp', category: 'Smileys', keywords: ['face', 'gasp', 'shock', 'surprise'] },
  { char: '🫡', name: 'salute', category: 'Smileys', keywords: ['face', 'salute', 'respect', 'army'] },
  { char: '🤫', name: 'shush', category: 'Smileys', keywords: ['face', 'shush', 'quiet', 'silent'] },
  { char: '🫠', name: 'melting', category: 'Smileys', keywords: ['face', 'melt', 'hot', 'sarcasm'] },
  { char: '🤥', name: 'lying', category: 'Smileys', keywords: ['face', 'lying', 'liar', 'pinocchio'] },
  { char: '😶', name: 'no_mouth', category: 'Smileys', keywords: ['face', 'silent', 'quiet'] },
  { char: '🫥', name: 'dotted_line_face', category: 'Smileys', keywords: ['face', 'invisible', 'hide', 'disappear'] },
  { char: '😐', name: 'neutral', category: 'Smileys', keywords: ['face', 'neutral', 'deadpan', 'meh'] },
  { char: '😑', name: 'expressionless', category: 'Smileys', keywords: ['face', 'expressionless', 'meh'] },
  { char: '😬', name: 'grimace', category: 'Smileys', keywords: ['face', 'grimace', 'awkward', 'nervous'] },
  { char: '🫨', name: 'shaking_face', category: 'Smileys', keywords: ['face', 'shake', 'shock', 'dizzy'] },
  { char: '🥱', name: 'yawn', category: 'Smileys', keywords: ['face', 'yawn', 'tired', 'sleepy'] },
  { char: '😴', name: 'sleeping', category: 'Smileys', keywords: ['face', 'sleep', 'snore', 'tired'] },
  { char: '🤤', name: 'drooling', category: 'Smileys', keywords: ['face', 'drool', 'desire'] },
  { char: '😪', name: 'sleepy', category: 'Smileys', keywords: ['face', 'sleepy', 'tear', 'tired'] },
  { char: '😮', name: 'gasp_open_mouth', category: 'Smileys', keywords: ['face', 'surprise', 'open', 'gasp'] },
  { char: '🤐', name: 'zipper_mouth', category: 'Smileys', keywords: ['face', 'zipper', 'silent', 'secret'] },
  { char: '🥴', name: 'woozy', category: 'Smileys', keywords: ['face', 'drunk', 'dizzy', 'woozy', 'weird'] },
  { char: '🤢', name: 'nauseous', category: 'Smileys', keywords: ['face', 'sick', 'vomit', 'green', 'nausea'] },
  { char: '🤮', name: 'vomit', category: 'Smileys', keywords: ['face', 'sick', 'vomit', 'puke'] },
  { char: '🤧', name: 'sneeze', category: 'Smileys', keywords: ['face', 'sick', 'sneeze', 'cold', 'allergy'] },
  { char: '😷', name: 'mask', category: 'Smileys', keywords: ['face', 'sick', 'mask', 'doctor'] },
  { char: '🤒', name: 'thermometer', category: 'Smileys', keywords: ['face', 'sick', 'thermometer', 'fever'] },
  { char: '🤕', name: 'bandage', category: 'Smileys', keywords: ['face', 'sick', 'bandage', 'hurt', 'injury'] },
  { char: '🤑', name: 'money_mouth', category: 'Smileys', keywords: ['face', 'money', 'rich', 'wealth'] },
  { char: '🤠', name: 'cowboy', category: 'Smileys', keywords: ['face', 'cowboy', 'hat', 'west'] },
  { char: '😈', name: 'devil_smile', category: 'Smileys', keywords: ['devil', 'demon', 'horns', 'evil'] },
  { char: '👿', name: 'devil_angry', category: 'Smileys', keywords: ['devil', 'demon', 'horns', 'angry'] },
  { char: '👹', name: 'ogre', category: 'Smileys', keywords: ['monster', 'japanese', 'ogre', 'mask'] },
  { char: '👺', name: 'goblin', category: 'Smileys', keywords: ['monster', 'japanese', 'goblin', 'mask', 'tengu'] },
  { char: '🤡', name: 'clown', category: 'Smileys', keywords: ['face', 'clown', 'circus', 'silly'] },
  { char: '💩', name: 'poop', category: 'Smileys', keywords: ['poop', 'shit', 'turd', 'funny'] },
  { char: '👻', name: 'ghost', category: 'Smileys', keywords: ['ghost', 'spooky', 'halloween'] },
  { char: '💀', name: 'skull', category: 'Smileys', keywords: ['skull', 'skeleton', 'death', 'dead'] },
  { char: '☠️', name: 'crossbones', category: 'Smileys', keywords: ['skull', 'crossbones', 'danger', 'pirate', 'poison'] },
  { char: '👽', name: 'alien', category: 'Smileys', keywords: ['alien', 'ufo', 'space'] },

  // People & Hands
  { char: '👋', name: 'wave', category: 'People', keywords: ['wave', 'hand', 'hello', 'bye', 'goodbye'] },
  { char: '🤚', name: 'raised_back_of_hand', category: 'People', keywords: ['hand', 'backhand', 'raised'] },
  { char: '🖐️', name: 'raised_hand_with_fingers_splayed', category: 'People', keywords: ['hand', 'splayed', 'fingers'] },
  { char: '✋', name: 'raised_hand', category: 'People', keywords: ['hand', 'highfive', 'stop'] },
  { char: '🖖', name: 'vulcan_salute', category: 'People', keywords: ['hand', 'vulcan', 'spock', 'star_trek'] },
  { char: '👌', name: 'ok_hand', category: 'People', keywords: ['hand', 'ok', 'okay', 'fine'] },
  { char: '🤌', name: 'pinched_fingers', category: 'People', keywords: ['hand', 'italian', 'question', 'sarcasm'] },
  { char: '🤏', name: 'pinched_hand', category: 'People', keywords: ['hand', 'pinch', 'small', 'little'] },
  { char: '✌️', name: 'peace_sign', category: 'People', keywords: ['hand', 'peace', 'victory', 'two'] },
  { char: '🤞', name: 'fingers_crossed', category: 'People', keywords: ['hand', 'luck', 'crossed', 'hope'] },
  { char: '🫰', name: 'hand_with_index_finger_and_thumb_crossed', category: 'People', keywords: ['hand', 'heart', 'snap', 'money', 'love'] },
  { char: '🤟', name: 'love_you_gesture', category: 'People', keywords: ['hand', 'love', 'ily'] },
  { char: '🤘', name: 'sign_of_the_horns', category: 'People', keywords: ['hand', 'horns', 'rock', 'metal'] },
  { char: '🤙', name: 'call_me', category: 'People', keywords: ['hand', 'call', 'phone'] },
  { char: '👈', name: 'point_left', category: 'People', keywords: ['hand', 'point', 'left'] },
  { char: '👉', name: 'point_right', category: 'People', keywords: ['hand', 'point', 'right'] },
  { char: '👆', name: 'point_up_backhand', category: 'People', keywords: ['hand', 'point', 'up'] },
  { char: '🖕', name: 'middle_finger', category: 'People', keywords: ['hand', 'middle', 'finger', 'rude'] },
  { char: '👇', name: 'point_down', category: 'People', keywords: ['hand', 'point', 'down'] },
  { char: '☝️', name: 'point_up', category: 'People', keywords: ['hand', 'point', 'up', 'one'] },
  { char: '👍', name: 'thumbsup', category: 'People', keywords: ['hand', 'thumbs', 'up', 'like', 'approve', 'ok'] },
  { char: '👎', name: 'thumbsdown', category: 'People', keywords: ['hand', 'thumbs', 'down', 'dislike', 'disapprove'] },
  { char: '✊', name: 'fist_raised', category: 'People', keywords: ['hand', 'fist', 'power', 'solidarity'] },
  { char: '👊', name: 'fist_oncoming', category: 'People', keywords: ['hand', 'fist', 'punch', 'bump'] },
  { char: '🤛', name: 'fist_left', category: 'People', keywords: ['hand', 'fist', 'punch', 'left'] },
  { char: '🤜', name: 'fist_right', category: 'People', keywords: ['hand', 'fist', 'punch', 'right'] },
  { char: '👏', name: 'clap', category: 'People', keywords: ['hand', 'clap', 'applause', 'bravo'] },
  { char: '🙌', name: 'raised_hands', category: 'People', keywords: ['hand', 'celebrate', 'hooray', 'raise'] },
  { char: '👐', name: 'open_hands', category: 'People', keywords: ['hand', 'open', 'hug'] },
  { char: '🤲', name: 'palms_up', category: 'People', keywords: ['hand', 'palms', 'pray', 'cupped'] },
  { char: '🤝', name: 'handshake', category: 'People', keywords: ['hand', 'handshake', 'deal', 'agreement', 'meet'] },
  { char: '🙏', name: 'pray', category: 'People', keywords: ['hand', 'pray', 'please', 'thanks', 'thankyou', 'hope'] },
  { char: '✍️', name: 'writing', category: 'People', keywords: ['hand', 'write', 'pen', 'pencil'] },
  { char: '💅', name: 'nail_polish', category: 'People', keywords: ['hand', 'nail', 'polish', 'manicure', 'sass'] },
  { char: '🤳', name: 'selfie', category: 'People', keywords: ['hand', 'phone', 'selfie', 'camera'] },
  { char: '💪', name: 'flex', category: 'People', keywords: ['hand', 'muscle', 'flex', 'strong', 'power'] },
  { char: '🧠', name: 'brain', category: 'People', keywords: ['brain', 'mind', 'think', 'smart'] },
  { char: '❤️', name: 'heart', category: 'Symbols & Flags', keywords: ['love', 'heart', 'red'] },

  // Nature
  { char: '🐶', name: 'dog', category: 'Nature', keywords: ['animal', 'dog', 'puppy', 'pet'] },
  { char: '🐱', name: 'cat', category: 'Nature', keywords: ['animal', 'cat', 'kitten', 'pet'] },
  { char: '🐻', name: 'bear', category: 'Nature', keywords: ['animal', 'bear', 'wild'] },
  { char: '🐯', name: 'tiger', category: 'Nature', keywords: ['animal', 'tiger', 'wild', 'cat'] },
  { char: '🦁', name: 'lion', category: 'Nature', keywords: ['animal', 'lion', 'wild', 'king'] },
  { char: '🐮', name: 'cow', category: 'Nature', keywords: ['animal', 'cow', 'farm'] },
  { char: '🐷', name: 'pig', category: 'Nature', keywords: ['animal', 'pig', 'farm'] },
  { char: '🐸', name: 'frog', category: 'Nature', keywords: ['animal', 'frog', 'amphibian'] },
  { char: '🐵', name: 'monkey', category: 'Nature', keywords: ['animal', 'monkey', 'ape'] },
  { char: '🐧', name: 'penguin', category: 'Nature', keywords: ['animal', 'penguin', 'bird', 'cold'] },
  { char: '🚀', name: 'rocket', category: 'Travel', keywords: ['space', 'rocket', 'launch', 'fast'] },
  { char: '🔥', name: 'fire', category: 'Nature', keywords: ['fire', 'hot', 'burn', 'flame', 'lit'] },
  { char: '⭐', name: 'star', category: 'Symbols & Flags', keywords: ['star', 'yellow', 'gold'] },
  { char: '🌟', name: 'sparkling_star', category: 'Symbols & Flags', keywords: ['star', 'sparkle', 'shine'] },
  { char: '✨', name: 'sparkles', category: 'Symbols & Flags', keywords: ['sparkles', 'magic', 'shine', 'clean'] },

  // Food
  { char: '🍔', name: 'burger', category: 'Food', keywords: ['food', 'burger', 'hamburger', 'fastfood'] },
  { char: '🍟', name: 'french_fries', category: 'Food', keywords: ['food', 'fries', 'french', 'fastfood'] },
  { char: '🍕', name: 'pizza', category: 'Food', keywords: ['food', 'pizza', 'cheese'] },
  { char: '🌭', name: 'hotdog', category: 'Food', keywords: ['food', 'hotdog'] },
  { char: '🥪', name: 'sandwich', category: 'Food', keywords: ['food', 'sandwich', 'bread'] },
  { char: '🌮', name: 'taco', category: 'Food', keywords: ['food', 'taco', 'mexican'] },
  { char: '🌯', name: 'burrito', category: 'Food', keywords: ['food', 'burrito', 'wrap'] },
  { char: '☕', name: 'coffee', category: 'Food', keywords: ['drink', 'coffee', 'cafe', 'tea', 'hot'] },
  { char: '🍺', name: 'beer', category: 'Food', keywords: ['drink', 'beer', 'alcohol', 'pub'] },

  // Activity
  { char: '⚽', name: 'soccer', category: 'Activity', keywords: ['sports', 'soccer', 'football', 'ball'] },
  { char: '🏀', name: 'basketball', category: 'Activity', keywords: ['sports', 'basketball', 'ball'] },
  { char: '🏈', name: 'football', category: 'Activity', keywords: ['sports', 'football', 'rugby', 'ball'] },
  { char: '🏆', name: 'trophy', category: 'Activity', keywords: ['trophy', 'prize', 'winner', 'cup', 'gold'] },
  { char: '🎯', name: 'dart', category: 'Activity', keywords: ['game', 'dart', 'target', 'bullseye'] },

  // Travel
  { char: '🌇', name: 'sunset', category: 'Travel', keywords: ['sunset', 'city', 'dusk', 'evening'] },
  { char: '✈️', name: 'airplane', category: 'Travel', keywords: ['travel', 'plane', 'airplane', 'flight'] },
  { char: '🚗', name: 'car', category: 'Travel', keywords: ['travel', 'car', 'automobile'] },

  // Objects
  { char: '💡', name: 'lightbulb', category: 'Objects', keywords: ['light', 'bulb', 'idea', 'inspiration'] },
  { char: '💻', name: 'laptop', category: 'Objects', keywords: ['computer', 'laptop', 'tech', 'work'] },
  { char: '📚', name: 'books', category: 'Objects', keywords: ['book', 'read', 'library', 'study'] },
  { char: '📝', name: 'memo', category: 'Objects', keywords: ['write', 'note', 'memo', 'document'] },
  { char: '📌', name: 'pushpin', category: 'Objects', keywords: ['pin', 'pushpin', 'board', 'note'] },
  { char: '🎉', name: 'tada', category: 'Objects', keywords: ['party', 'celebrate', 'tada', 'congratulations'] }
];
